# Generated by Django 5.0.6 on 2024-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(choices=[('False', 'False'), ('True', 'True')], default=False),
        ),
    ]
